#!/bin/sh
#
# 2014 ungleich GmbH (cdist at ungleich.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


user="$__object_id"
state=$(cat "$__object/parameter/state")


################################################################################
# not at ungleich GmbH (anymore)
#
set --
for key in henk tobias; do
    keyfile="$__type/files/${key}.pub"
    set -- "$@" --key
    set -- "$@" "$(echo $(cat "$keyfile"))"
done

__ssh_authorized_keys "ungleich-staff-absent-$user" \
    --owner "$user" --state absent "$@"

################################################################################
# currently at ungleich GmbH
#
set --
for key in dave nico dominique carlos ; do
    keyfile="$__type/files/${key}.pub"

    set -- "$@" --key
    set -- "$@" "$(echo $(cat "$keyfile"))"
done

__ssh_authorized_keys "ungleich-staff-$user" \
    --owner "$user" --state "$state" "$@"
